### ISSUE TITLE
 Padding Error in Responsive Mode

### ISSUE THREAD

**Issue by 0xkuze** [carlosazaustre/website#51]
### Description
Padding error in last blog post in responsive mode

### Play
1-https://carlosazaustre.es/workspace
2-Active Responsive Mode or see from the mobile

### Screenshots
![Screenshot](https://user-images.githubusercontent.com/65286318/123262930-46f7ae80-d4ad-11eb-93f5-36206afc5217.png)

### Context

The problem is only in this post

**Comment by carlosazaustre** [comment]
Gracias @kuzeofficial !
Lo tengo contemplado, es debido a las Tablas que en ChakraUI no son responsive.
Issue #50
